# main.yml - Install Python 2.7, either from a repo or a built RPM
---
- name: DEBUG!
  debug:
    var: custom_repo
  tags:
    - python2
    - debugpy

- name: DEBUG True!
  debug:
    msg: The var is True!
  when: custom_repo
  tags:
    - python2
    - debugpy

- name: DEBUG False!
  debug:
    msg: The var is True!
  when: not custom_repo
  tags:
    - python2
    - debugpy

- name: Install Python27 from repo
  yum:
    name: python27
    state: latest
    disable_gpg_check: yes
  tags:
    - python2
